1.
问题描述: Terminal中可以正常运行,Pycharm中无法正常运行新建的项目

(django20) atlednolispedeMacBook-Pro:blog atlednolispe$ python3 manage.py startapp config
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/atlednolispe/.virtualenvs/django20/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/atlednolispe/.virtualenvs/django20/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/atlednolispe/.virtualenvs/django20/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/atlednolispe/.virtualenvs/django20/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/atlednolispe/.virtualenvs/django20/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_fCreate basic model definition.
rames_removed
  File "/Users/atlednolispe/atlednolispe/Projects/PycharmProjects/blog/epsilon/models.py", line 5, in <module>
    class Post(models.Model):
  File "/Users/atlednolispe/atlednolispe/Projects/PycharmProjects/blog/epsilon/models.py", line 14, in Post
    category = models.ForeignKey('Category', verbose_name="种类")
TypeError: __init__() missing 1 required positional argument: 'on_delete'

原因:
models.ForeignKey类型的字段中on_delete为必填项

解决方案:
category = models.ForeignKey('Category', verbose_name="种类")
涉及外键的字段增加on_delete的关键字参数
category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name="种类")

# 项目操作
1.创建数据库的migrations
(django20) atlednolispedeMacBook-Pro:blog atlednolispe$ python3 manage.py makemigrations
Migrations for 'config':
  config/migrations/0001_initial.py
    - Create model Link
    - Create model SideBar
Migrations for 'epsilon':
  epsilon/migrations/0001_initial.py
    - Create model Category
    - Create model Post
    - Create model Tag
    - Add field tags to post
Migrations for 'comment':
  comment/migrations/0001_initial.py
    - Create model Comment

2.在数据库中生效migrate
(django20) atlednolispededeMacBook-Pro:blog atlednolispede$ python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, comment, config, contenttypes, epsilon, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying epsilon.0001_initial... OK
  Applying comment.0001_initial... OK
  Applying config.0001_initial... OK
  Applying sessions.0001_initial... OK

# QuerySet
1.懒加载+链式调用
posts = Post.objects.all()
available_posts = posts.filter(status=1)
print(available_posts)  # 此时才真正查询对象

# connection
from django.db import connection
connection.queries